# Generated by Django 4.2.11 on 2025-06-05 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1_filename', models.CharField(max_length=255)),
                ('image1_hash', models.CharField(max_length=64)),
                ('image1_size', models.PositiveIntegerField()),
                ('image2_filename', models.CharField(max_length=255)),
                ('image2_hash', models.CharField(max_length=64)),
                ('image2_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('are_identical', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('comparison_results', models.JSONField(blank=True, default=dict)),
                ('comparison_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Comparison',
                'verbose_name_plural': 'Image Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('image_format', models.CharField(max_length=10)),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ela_analysis_performed', models.BooleanField(default=False)),
                ('ela_quality', models.PositiveIntegerField(default=95)),
                ('ela_results', models.JSONField(blank=True, default=dict)),
                ('steganography_result', models.TextField(blank=True, null=True)),
                ('steganography_message', models.TextField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('analysis_duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
