# Generated by Django 5.2.1 on 2026-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='rgb_histogram_data',
            field=models.JSONField(blank=True, default=dict, help_text='RGB histogram bins for color analysis'),
        ),
    ]
