# Generated by Django 5.2.1 on 2026-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_imageanalysis_ahash_imageanalysis_copy_move_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='deepfake_notes',
            field=models.TextField(blank=True, help_text='Explanation or heuristic reasoning for the AI detection score', null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='deepfake_probability',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0 to 100.0) that the image is AI-generated', null=True),
        ),
    ]
