# Generated by Django 4.2.11 on 2026-04-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_imageanalysis_deepfake_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='deepfake_notes',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='deepfake_probability',
        ),
    ]
