# Generated by Django 4.2.11 on 2026-04-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_imageanalysis_deepfake_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='deepfake_notes',
            field=models.TextField(blank=True, help_text='Explanation or heuristic reasoning for the AI detection score', null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='deepfake_probability',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0 to 100.0) that the image is AI-generated', null=True),
        ),
    ]
