# Generated by Django 5.2.1 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_imageanalysis_deepfake_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='ela_heatmap_b64',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of the ELA difference heatmap visualization', null=True),
        ),
    ]
