# Generated by Django 4.2.11 on 2025-06-05 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('comparison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.imagecomparison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparison Report',
                'verbose_name_plural': 'Comparison Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.imageanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Report',
                'verbose_name_plural': 'Analysis Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
